name: alethic-ism-api
channels:
  - https://conda.anaconda.org/quantumwake
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - python-multipart
  - restrictedpython
  - redis-py
  - pyyaml
  - fastapi
  - pydantic
  - nats-py   # message bus provider NATS
  - mako
  - pyjwt
  - datasets
  - uvicorn
  - alethic-ism-core
  - alethic-ism-db
