name: alethic-ism-api
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - python-multipart
  - pulsar-client
  - restrictedpython
# via pip  - firebase-admin
  - pyyaml
  - fastapi
  - pydantic
  - uvicorn
  - alethic-ism-core
  - alethic-ism-db
