name: alethic-ism-api
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - python-dotenv
  - psycopg2
#  - pulsar-client
  - pyyaml
  - fastapi
  - pydantic
  - uvicorn
  - alethic-ism-core
  - alethic-ism-db
