name: alethic-ism-api
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - python-multipart
  - restrictedpython
  - redis-py
  - pyyaml
  - fastapi
  - pydantic
  - nats-py   # message bus provider NATS
  - mako
  - datasets
  - uvicorn
  - alethic-ism-core
  - alethic-ism-db
