apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-api-secret
  namespace: alethic
stringData:
#  ROUTING_FILE: "/app/config/routing.yaml/routing.yaml"
  DATABASE_URL: "postgresql://ism_db_user:0aa0a535d1b592d1@alethic-db-service:5432/ism_db"
  .firebase-credentials.json: |
    {
      "type": "service_account",
      "project_id": "quantum-ism",
      "private_key_id": "699289861f2f6dcf67698285326ac1931b6e286e",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4M9lD5iPOMowp\ngkDs/jOKSA/CP2NSgXw4nkViRsKCYZmgIuS1Hy5f7XBHyZhN/cgtflpQVuoMHztv\ncrYEwjz0nQSaFc8H/rhw+nZAnFC15Tc+2Qweks7ljfP1dxbQzCu7bHC7tm9cS/FO\nS7k9pX/IhHzuTlAHFiWS1pWKpO94jj2v0hS5W99bxoK49WJ2KaHcaXYTYYyuNiLt\nszkLwPoF2jpVTVdkIpcgF5cafV2UcLK/A+NueJVfg4PAyzgUN5cyormO8xuIAZDt\nKDMNzIM1bdAY3DuurvmmM4MqkIjHrVNAZNq4lCLQvIf/QPSAvYxzs1Ask9H2/8ti\n33hpSf57AgMBAAECggEAOHNnV6gte/FAxC3PYPHscKnx7mlHso7NN3rFr78YuCVa\nE9nttlY2e56EJPPysaAfW1XYLrvcIVfm+powjxfJ33tJYEFjv8L/2lvfpqBhGcWD\n30ZcMPhz4KTWyXi0LMwNcPRkPhrEWQhLDOAnBm30UcrMkKm+W9WdMTmC/cjbPNnw\nkcOvbo8TsiA0zCjy6pn0qD4Ul349ri/PIs3PMudmyouhtEweGfap2svsL6zQmMyO\nyt5YZElwK2sZloQgne5TzKKokydNyDR1O2DGec1xiJbpLULn23ouHeGlA3xAbFrF\nOl73C8HJvZ7eL3H052xwK76/VHBmyukhD7o0n3r6KQKBgQD1h3npHk3lwLeh2BFg\nwUZTGbNynC9ZbgGFn0wocQIGU0X7gI3QLZ4gruq6WVP1s9qN5i/ZgKBSiFqWMBD2\n9o2a4rbSLxKJHUF1o/k2xaezYMWcDqqetkWymRUq5uDO0BAmFl7uqkftTk2gRRGC\nYhS/YwcbzK2YGSQD3dFsf4mZwwKBgQDADtlP0hyIxJEz0CBW7t2LCNs8Aa9kAXgY\nR5cpk+zpfRP/NAPf0rl2pYOGCo93kp3IuaL+omIkokkRO+SQQYaoHjSn+KDsxJhO\nuz4KYMh7GAis7A3yq6qMo1dfVJqC+qA/R++V5TtSBhfZ+gDkdEicbGoDTLAb/FXm\ni7LWRmIE6QKBgQCEww2jhPRgEFX7GGdFJx0MoDAM//EGbVo7U4iNsZWDsBF+TePg\ntlnzmEFqJBUnHWpHIjmrZUbLedlprnHt6CFnp8FtY3ClXYFgyBpgiH4Gm4Qevzt4\n+Fw1l1r/yLm0eoLQ5XXNnZuo8Jc+2zn9g2Vum3BjksgnHyj/QjkUbt4LmwKBgFPK\nJqTcVfaVS4P/WRyUObNeuccENTC8M1jkYt6Q2ttC5maAmvAbTy6kJy1jjhPss0nP\nM31D+u1gn+AU8TK+Y7EU/IQLxKmHW6t9pSOB9fU+FwraMXudyVpyKLw+fOqHzUHO\ncIhE6gxu/BjtKVaCJOuZoOavnmWXQSLD79HsAveBAoGAdwH0LrEKEpX22s/h53ON\nDEE1+K7XohuZiaSZRjORIPi1WyCg1tIGbbWKgNEqjAQD4kGZ2RvzveQXsaMK8BgL\nKHJRrTjebj5k5l02L4QbysHV9expyp5XZoteHsATDbnIo0ibzh+y3abBt36VDeel\nKn8JRSr/FNhKRODMCYhFJEE=\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk-vnxbq@quantum-ism.iam.gserviceaccount.com",
      "client_id": "112652730092705729072",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-vnxbq%40quantum-ism.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

        topic_routes:
          - selector: state/router
            topic: ism_state_router
            subscription: ism_state_router_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

