name: Docker Image CI for Alethic ISM API

on:
  push:
    branches: [ "main" ]
    tags:   [ "v*" ]          # production on tags like v1.2.3
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0         # fetch all history & tags

      - name: Initialize helper scripts
        run: make init

      - name: Build Docker image
        run: make build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: make push

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 qwake-k8s-cluster

      - name: Deploy to Kubernetes
        run: make deploy

      - name: Verify rollout
        run: kubectl rollout status deployment/alethic-ism-api-deployment -n alethic
