name: Docker Image CI for Workload API

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  build-push-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Workload API code
      id: code_checkout
      uses: actions/checkout@v3

    - name: Assign Environment Variables for Build & Deployment Process
      id: setup_variables

      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | head -c7)
        TAG="krasaee/alethic-ism-api:$COMMIT_ID"

        echo "COMMIT_ID=$COMMIT_ID" >> "$GITHUB_ENV" # for local variables
        echo "TAG=$TAG" >> "$GITHUB_ENV" # for local variables

    - name: Build container image
      id: build_docker_image

      run: |
        echo "COMMIT ID: $COMMIT_ID"
        echo "DOCKER TAG: $TAG"
        
        # build the docker image
        echo "Building with the fully qualified registry tag $TAG"
        ./docker_build_conda_package.sh $TAG
  
        # pass the tag to the next step
        echo "TAG=$TAG" >> "$GITHUB_ENV" # for local variables

    - name: Login to Docker Hub
      id: dockerhub_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push container image to Docker Hub Container Registry
      id: push_docker_image
      run: |
        echo "Pushing container file with tag $TAG"
        docker push $TAG
